# Generated by Django 4.2.6 on 2023-10-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='оплаченный курс или урок'),
        ),
    ]
