# Generated by Django 4.2.6 on 2023-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_payments_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='url',
            field=models.CharField(default='не предоставлена', max_length=50, verbose_name='ссылка на оплату'),
        ),
    ]
