# Generated by Django 4.2.6 on 2023-10-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_payments_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='url',
            field=models.CharField(default='не предоставлена', max_length=500, verbose_name='ссылка на оплату'),
        ),
    ]
