# Generated by Django 4.2.6 on 2023-10-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_payments_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='url_session_checkout',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
