# Generated by Django 4.2.6 on 2023-10-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_payments_url_session_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='url_session_checkout',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
