# Generated by Django 4.2.6 on 2023-10-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_payments_url_session_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='url_session_checkout',
        ),
        migrations.AddField(
            model_name='payments',
            name='url_session_checkout_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
