# Generated by Django 4.2.6 on 2023-10-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_rename_url_session_checkout_payments_url_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='url_session',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='session checkout id'),
        ),
    ]
