# Generated by Django 4.2.6 on 2023-10-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
